name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node: ["22", "24"]
        os: [macOS-latest, windows-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            cache_path: ~/.cache/deno/
          - os: macos-latest
            cache_path: ~/Library/Caches/deno/
          - os: windows-latest
            cache_path: ~\AppData\Local\deno\

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Verify formatting
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == '24'
        run: npm run format:check

      - name: Run linter
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == '24'
        run: npm run lint

      - name: Run knip
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == '24'
        run: npm run knip

      - name: Typo check
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == '24'
        uses: crate-ci/typos@master

      - name: Type check project
        run: npm run check:types

      - name: Run tests
        run: npm run test
